work_dir: ./work_dir/pingpong-109-coco/msg3d_joint

# feeder
feeder: feeders.feeder.Feeder
train_feeder_args:
  data_path: ../dataset/2023-3-29_北体合作_示范动作/MS-G3D/pingpong-109-coco/train_data_joint.npy
  label_path: ../dataset/2023-3-29_北体合作_示范动作/MS-G3D/pingpong-109-coco/train_label.pkl
  debug: False
  random_choose: False
  random_shift: False
  random_move: False
  window_size: -1
  normalization: False

test_feeder_args:
  data_path: ../dataset/2023-3-29_北体合作_示范动作/MS-G3D/pingpong-109-coco/val_data_joint.npy
  label_path: ../dataset/2023-3-29_北体合作_示范动作/MS-G3D/pingpong-109-coco/val_label.pkl

# model
model: model.msg3d.Model
model_args:
  num_class: 29
  num_point: 17
  num_person: 8
  num_gcn_scales: 8    # `num_scales` == `K + 1` in the paper
  num_g3d_scales: 6
  graph: graph.pingpong-coco.AdjMatrixGraph

# optim
weight_decay: 0.0005
base_lr: 0.05
step: [ 30, 40 ]

# training
num_epoch: 50
device: [ 0, 1, 2, 3, 4, 5 ]
batch_size: 32 # 32 origin
forward_batch_size: 16
test_batch_size: 32
nesterov: True

